---
NONMEM_directory: C:/nm74g64
NONMEM_version: '7.4'
PsN_version: 4.8.1
command_line: c:\Strawberry\perl\bin\bootstrap -samples=50 -threads=4 -dir=bs_C02-1
  C02-1.ctl
common_options:
  abort_on_fail: 0
  accepted_ofv_difference: 0.5
  add_retries: 0
  always_datafile_in_nmrun: 0
  check_nmtran: 0
  clean: 1
  compress: 0
  condition_number_limit: 1000
  correlation_limit: 0.85
  crash_restarts: 4
  degree: 0.1
  directory: C:\nma\examples\THEO-pirana\bs_C02-1\
  display_iterations: 0
  handle_crashes: 1
  handle_msfo: 0
  large_omega_cv_limit: 0.8
  large_sigma_cv_limit: 0.8
  large_theta_cv_limit: 0.5
  last_est_complete: 0
  lsf_sleep: 3
  min_retries: 0
  missing_data_token: '-99'
  model_subdir: 0
  near_bound_sign_digits: 2
  near_zero_boundary_limit: 0.01
  nice: 19
  nm_output: ext,cov,cor,coi,phi
  nm_version: default
  nmfe: '1'
  nmqual: 0
  nodes: 0
  picky: 0
  prepend_model_file_name: 1
  quick_summarize: 0
  retries: 0
  rmarkdown: 1
  rplots: 0
  run_on_lsf: 0
  run_on_sge: 0
  run_on_slurm: 0
  run_on_torque: 0
  run_on_ud: 0
  run_on_zink: 0
  seed: 331836
  send_email: 0
  shrinkage: 0
  sign_digits_off_diagonals: 2
  significant_digits_accept: 0
  so: 0
  template_directory_rplots: C:/STRAWB~1/perl/site/lib/PsN_4_8_1/R-scripts
  template_file_rplots: bootstrap_default.Rmd
  threads: 4
  tweak_inits: 1
  verbose: 0
  zip: 0
copied_files:
- C02-1.lst
- C02-1.ext
- C02-1.cov
- C02-1.cor
- C02-1.coi
- C02-1.phi
- sdtabC02-1
- patabC02-1
finish_time: 2018-10-19 18:11:00
model_files:
- C:\nma\examples\THEO-pirana\C02-1.ctl
start_time: 2018-10-19 18:08:34
tool_name: bootstrap
tool_options:
  allow_ignore_id: 0
  copy_data: 1
  dofv: 0
  keep_covariance: 0
  keep_tables: 0
  mceta: 0
  run_base_model: 1
  samples: 50
  skip_covariance_step_terminated: '0'
  skip_estimate_near_boundary: '1'
  skip_minimization_terminated: '1'
  skip_with_covstep_warnings: '0'
  type: bootstrap
  update_inits: 1
