      SUBROUTINE MUMODEL2(THETA,MU_,ICALL,IDEF,NEWIND,&
      EVTREC,DATREC,IREV,NVNT,INDXS,F,G,H,IRGG,GG,NETAS)
      USE NMPRD4P
      USE SIZES,     ONLY: DPSIZE,ISIZE
      USE PRDIMS,    ONLY: GPRD,HPRD,GERD,HERD,GPKD
      USE NMBAYES_REAL,    ONLY: PRIORINFO
      USE NMPRD_REAL,ONLY: ETA,EPS
      USE ROCM_REAL, ONLY: THETAF,OMEGAF,SIGMAF,THETAFR
      USE ROCM_REAL, ONLY: SETHET=>SETH,SEOMEG=>SEOM,SESIGM=>SESIG,SETHETR=>SETHR
      USE ROCM_REAL, ONLY: OBJECT
      USE ROCM_INT,  ONLY: IERE=>IEST_ERR,IERC=>ICOV_ERR
      USE ROCM_INT,  ONLY: NREP,IREP=>NCREP
      USE NMPRD_INT, ONLY: MSEC=>ISECDER,MFIRST=>IFRSTDER,IFIRSTEM
      USE NMPRD_INT, ONLY: MDVRES,ETASXI,NPDE_MODE,NOFIRSTDERCODE
      USE NMPRD_REAL, ONLY: DV_LOQ,CDF_L,DV_LAQ,CDF_LA
      USE NMPRD_INT, ONLY: NEWL2
      USE NMPRD_INT, ONLY: NTHES_=>NWTHT,NETAS_=>NWETA,NEPSS_=>NWEPS
      USE NMBAYES_REAL, ONLY: LDF
      USE NMPRD_INT, ONLY: U06,U29,UST
      IMPLICIT REAL(KIND=DPSIZE) (A-Z)
      REAL(KIND=DPSIZE)   :: MU_(*)
      REAL(KIND=DPSIZE) :: DATREC
 991  FORMAT (35F14.4)
 992  FORMAT (35E15.7)
 998  FORMAT (1PE22.15,1X,1PE22.15/)
 993  FORMAT ('(',I2,'E15.7)')
      CHARACTER*80 FMT(3)
      SAVE
      INTEGER(KIND=ISIZE) :: ICALL,NEWIND,INDXS
      REAL(KIND=DPSIZE) :: G(GPRD,*),H(HPRD,*)
      DIMENSION :: THETA(*),DATREC(*),INDXS(*)
      RETURN
      END
