      SUBROUTINE MUMODEL2(THETA,MU_,ICALL,IDEF,NEWIND,&
      EVTREC,DATREC,IREV,NVNT,INDXS,F,G,H,IRGG,GG,NETAS)
      USE NMPRD4P
      USE SIZES,     ONLY: DPSIZE,ISIZE
      USE PRDIMS,    ONLY: GPRD,HPRD,GERD,HERD,GPKD
      USE NMPRD_REAL,ONLY: ETA,EPS
      USE NMPRD_INT, ONLY: IERPRD,NETEXT,IQUIT
      USE NMPRD_CHAR,ONLY: ETEXT
      USE NMPRD_INT, ONLY: I_REC=>IRECRSIV
      USE NMPR_INT,  ONLY: RPTI=>NRPT_IN,RPTO=>NRPT_OUT,RPTON=>NRPT_ON,PRDFL=>IUSEPRD
      USE ROCM_REAL, ONLY: THETAF,OMEGAF,SIGMAF,THETAFR
      USE ROCM_REAL, ONLY: SETHET=>SETH,SEOMEG=>SEOM,SESIGM=>SESIG,SETHETR=>SETHR
      USE ROCM_REAL, ONLY: OBJECT
      USE ROCM_INT,  ONLY: IERE=>IEST_ERR,IERC=>ICOV_ERR
      USE NMPRD_REAL, ONLY: CORRL2
      USE ROCM_INT,  ONLY: NREP,IREP=>NCREP
      USE ROCM_INT,  ONLY: MIXNUM=>MIXCALL,MIXEST=>IMIXEST
      USE ROCM_REAL, ONLY: MIXP
      USE NMPRD_INT, ONLY: MSEC=>ISECDER,MFIRST=>IFRSTDER,IFIRSTEM
      USE NMPRD_INT, ONLY: MDVRES,ETASXI,NPDE_MODE,NOFIRSTDERCODE
      USE NMPRD_REAL, ONLY: DV_LOQ,CDF_L
      USE NMPRD_INT, ONLY: NPROB,IPROB,IDXSUP,NITR_SUP,NITSUP
      USE NMPRD_INT, ONLY: NEWL2
      USE ROCM_REAL, ONLY: TEMPLT=>VRAW
      USE ROCM_INT,  ONLY: NIREC=>NINDREC,NDREC=>NDATINDR
      USE ROCM_INT,  ONLY: NINDR=>NINDOBS,INDR1=>IDXOBSF,INDR2=>IDXOBSL
      USE ROCM_INT,  ONLY: LIREC=>NDATPASS
      USE ROCM_REAL, ONLY: APPND
      USE NMPR_REAL, ONLY: YLO,YUP
      USE NMPR_REAL, ONLY: CTLO=>CTLW,DCTLO=>DCTLW,DDCTLO=>DDCTLW
      USE NMPR_REAL, ONLY: CTUP,DCTUP,DDCTUP
      USE NMPR_INT,  ONLY: SKIP_=>SKIP
      USE NMPR_REAL, ONLY: THSIMP=>THET_P,OMSIMP=>OMEG_P,SGSIMP=>SIGM_P,THSIMPR
      USE ROCM_REAL, ONLY: DEN_NP
      USE NMPR_INT,  ONLY: F_FLAG=>IPRDFLG1
      USE ROCM_REAL, ONLY: OMEGA=>VARNF
      USE NMPRD_INT, ONLY: NTHES_=>NWTHT,NETAS_=>NWETA,NEPSS_=>NWEPS
      USE ROCM_REAL, ONLY: PR_Y
      USE ROCM_REAL, ONLY: PR_CT
      USE ROCM_REAL, ONLY: IIDX=>DIDVALX
      USE ROCM_REAL, ONLY: CNTID=>OFV_IND
      USE CMNM1_INT, ONLY: NIND_7=>NIND
      USE NMPRD_INT, ONLY: COMACT,COMSAV
      USE NMBAYES_REAL, ONLY: LDF
      USE NMPRD_INT, ONLY: U06,U29,UST
      IMPLICIT REAL(KIND=DPSIZE) (A-Z)
      REAL(KIND=DPSIZE)   :: MU_(*)
      REAL(KIND=DPSIZE) :: DATREC
 991  FORMAT (35F14.4)
 992  FORMAT (35E15.7)
 998  FORMAT (1PE22.15,1X,1PE22.15/)
 993  FORMAT ('(',I2,'E15.7)')
      CHARACTER*80 FMT(3)
      SAVE
      INTEGER(KIND=ISIZE) :: ICALL,NEWIND,INDXS
      REAL(KIND=DPSIZE) :: G(GPRD,*),H(HPRD,*)
      DIMENSION :: THETA(*),DATREC(*),INDXS(*)
      RETURN
      END
